### ISSUE TITLE
Run at different resolution

### ISSUE THREAD

**Issue by chenggang108** [GuangyWang/TADsplimer#1]
Hi 

The default resolution is 10K. Can I run it at a different resolution?

Thanks

**Comment by GuangyWang** [comment]
Yes, it works on any resolutions. But the suggested resolution (10Kb) has the best performance.

**Comment by GuangyWang** [comment]
> Hi
> 
> The default resolution is 10K. Can I run it at a different resolution?
> 
> Thanks

Yes, it works on any resolutions. But the suggested resolution (10Kb) has the best performance.
