### ISSUE TITLE
cannot run example files

### ISSUE THREAD

**Issue by KunFang93** [GuangyWang/TADsplimer#5]
Hi, Guangyu

I meet this error when I am running command : docker run -v /Users/KunFang/Downloads/:/data/ -t guangywang/tadsplimer:v1.0.3 python3 /bin/TADsplimer.py split_TADs -c /data/simulation_merge.txt,/data/simulation_split.txt --contact_maps_aliases merge,split -o /data/

Error message:
/data/simulation_merge.txt
auto: 2.1903446166505756 0.24093790783156332
There were 50 or more warnings (use warnings() to see the first 50)
There were 50 or more warnings (use warnings() to see the first 50)
/data/simulation_split.txt
Traceback (most recent call last):
  File "/bin/TADsplimer.py", line 386, in <module>
    split_TADs(command='split_TADs')
  File "/bin/TADsplimer.py", line 263, in split_TADs
    up2, down2, files2 = TAD_calling.file_split(file[1], outfile=tmp_dir2, print_subcontact=0, aliases=aliases[1])
  File "/bin/TAD_calling.py", line 41, in file_split
    contact_map = np.loadtxt(file)
  File "/opt/conda/lib/python3.5/site-packages/numpy/lib/npyio.py", line 926, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/opt/conda/lib/python3.5/site-packages/numpy/lib/_datasource.py", line 262, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/opt/conda/lib/python3.5/site-packages/numpy/lib/_datasource.py", line 618, in open
    raise IOError("%s not found." % path)
OSError: /data/simulation_split.txt not found.

However, I double-check but find that the simulation_split.txt indeed in the /data directory.
I was wondering if you have any suggestion to solve this problem? And I was also wondering what is the TAD.txt input format for TAD_matching? Thanks a lot!

Best,
Kun

**Comment by GuangyWang** [comment]
> Hi, Guangyu
> 
> I meet this error when I am running command : docker run -v /Users/KunFang/Downloads/:/data/ -t guangywang/tadsplimer:v1.0.3 python3 /bin/TADsplimer.py split_TADs -c /data/simulation_merge.txt,/data/simulation_split.txt --contact_maps_aliases merge,split -o /data/
> 
> Error message:
> /data/simulation_merge.txt
> auto: 2.1903446166505756 0.24093790783156332
> There were 50 or more warnings (use warnings() to see the first 50)
> There were 50 or more warnings (use warnings() to see the first 50)
> /data/simulation_split.txt
> Traceback (most recent call last):
> File "/bin/TADsplimer.py", line 386, in 
> split_TADs(command='split_TADs')
> File "/bin/TADsplimer.py", line 263, in split_TADs
> up2, down2, files2 = TAD_calling.file_split(file[1], outfile=tmp_dir2, print_subcontact=0, aliases=aliases[1])
> File "/bin/TAD_calling.py", line 41, in file_split
> contact_map = np.loadtxt(file)
> File "/opt/conda/lib/python3.5/site-packages/numpy/lib/npyio.py", line 926, in loadtxt
> fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
> File "/opt/conda/lib/python3.5/site-packages/numpy/lib/_datasource.py", line 262, in open
> return ds.open(path, mode, encoding=encoding, newline=newline)
> File "/opt/conda/lib/python3.5/site-packages/numpy/lib/_datasource.py", line 618, in open
> raise IOError("%s not found." % path)
> OSError: /data/simulation_split.txt not found.
> 
> However, I double-check but find that the simulation_split.txt indeed in the /data directory.
> I was wondering if you have any suggestion to solve this problem? And I was also wondering what is the TAD.txt input format for TAD_matching? Thanks a lot!
> 
> Best,
> Kun

Hi Kun,

I have tested TADsplimer. Following is my command. 

docker run -v /Users/yuchunchun/Downloads/TADsplimer-master/example/:/data/ -t guangywang/tadsplimer:v1.0.3 python3 /bin/TADsplimer.py split_TADs -c /data/simulation_merge.txt,/data/simulation_split.txt --contact_maps_aliases merge,split -o /data/

It is okay. If you directly downloaded my Git and didn’t change the path of test files. The test files should be in the folder: <your download path>/TADsplimer-master/example/ . You can use following command to check if the path is correct:

less <your download path>/TADsplimer-master/example/simulation_split.txt

If you have any questions, please let me know. In case I missed your questions, I can also send questions to my email, guangywang@gmail.com.

Best,
Guangyu

**Comment by KunFang93** [comment]
Hi, Guangyu

Thanks for your reply! I will try your suggestion.

Best,
Kun
